# Generated by Django 3.2.5 on 2021-07-15 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0002_borrowbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isBorrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='borrowbook',
            unique_together={('user', 'book')},
        ),
    ]
